"use client";

import { useState, type FormEvent } from "react";
import Image from "next/image";
import { ArrowDown, ArrowUp, Handshake, Loader2, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import type { LandingSection } from "@/components/dashboard/landing/types";

type Selection = LandingSection["partnerSelections"][number];
type Draft = { slug: string; name: string; type: "LOCAL" | "GLOBAL"; description: string; websiteUrl: string; isActive: boolean };
const emptyDraft: Draft = { slug: "", name: "", type: "LOCAL", description: "", websiteUrl: "", isActive: true };
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function fromSelection(selection: Selection): Draft { const partner = selection.partner; return { slug: partner.slug, name: partner.name, type: partner.type, description: partner.description ?? "", websiteUrl: partner.websiteUrl ?? "", isActive: partner.isActive }; }
async function request(url: string, init: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...init.headers } }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error?.message ?? "Partner request failed."); return payload.data; }

export function PartnersEditor({ section, onChanged }: { section: LandingSection; onChanged: () => Promise<void> | void }) {
  const [editingId, setEditingId] = useState<string | "new" | null>(null); const [draft, setDraft] = useState<Draft>(emptyDraft); const [pending, setPending] = useState(false);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const input = { slug: draft.slug || slugify(draft.name), name: draft.name, type: draft.type, description: draft.description || null, websiteUrl: draft.websiteUrl || null, isActive: draft.isActive }; try { if (editingId === "new") await request(`/api/v1/admin/landing/sections/${section.id}/partners`, { method: "POST", body: JSON.stringify(input) }); else if (editingId) await request(`/api/v1/admin/partners/${editingId}`, { method: "PATCH", body: JSON.stringify(input) }); setEditingId(null); await onChanged(); toast.success(editingId === "new" ? "Partner added." : "Partner updated."); } catch (error) { toast.error(error instanceof Error ? error.message : "Partner save failed."); } finally { setPending(false); } }
  async function remove(selection: Selection) { const partner = selection.partner; if (!window.confirm(`Delete “${partner.name}”?`)) return; setPending(true); try { await request(`/api/v1/admin/partners/${partner.id}`, { method: "DELETE" }); await onChanged(); toast.success("Partner deleted."); } catch (error) { toast.error(error instanceof Error ? error.message : "Delete failed."); } finally { setPending(false); } }
  async function move(index: number, direction: -1 | 1) { const destination = index + direction; if (destination < 0 || destination >= section.partnerSelections.length) return; const reordered = [...section.partnerSelections]; [reordered[index], reordered[destination]] = [reordered[destination], reordered[index]]; setPending(true); try { await request(`/api/v1/admin/landing/sections/${section.id}/selections/partners`, { method: "PUT", body: JSON.stringify({ entries: reordered.map((entry, sortOrder) => ({ id: entry.partner.id, sortOrder })) }) }); await onChanged(); toast.success("Partner order updated."); } catch (error) { toast.error(error instanceof Error ? error.message : "Reorder failed."); } finally { setPending(false); } }

  return <section className="mt-6 border-t border-slate-200 pt-5"><div className="mb-4 flex items-center justify-between gap-3"><div><h4 className="flex items-center gap-2 text-sm font-black text-slate-900"><Handshake className="size-4 text-[#0193CD]" /> Partners</h4><p className="mt-1 text-xs text-slate-400">Manage national and global partner logos shown on the homepage.</p></div><button type="button" onClick={() => { setDraft(emptyDraft); setEditingId("new"); }} className="inline-flex h-9 items-center gap-2 rounded-xl bg-[#0193CD] px-3 text-xs font-black text-white"><Plus className="size-3.5" /> Add partner</button></div><div className="space-y-3">{section.partnerSelections.map((selection, index) => { const partner = selection.partner; return <article key={partner.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center gap-3 p-3"><div className="relative size-12 shrink-0 overflow-hidden rounded-xl bg-slate-100">{partner.logo?.url ? <Image src={partner.logo.url} alt="" fill sizes="48px" className="object-contain p-1" /> : null}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-800">{partner.name}</p><p className="text-[11px] text-slate-400">{partner.type === "GLOBAL" ? "Global" : "National"}{partner.isActive ? "" : " · inactive"}</p></div><Button label="Move up" disabled={pending || index === 0} onClick={() => void move(index, -1)}><ArrowUp className="size-3.5" /></Button><Button label="Move down" disabled={pending || index === section.partnerSelections.length - 1} onClick={() => void move(index, 1)}><ArrowDown className="size-3.5" /></Button><Button label="Edit" onClick={() => { setDraft(fromSelection(selection)); setEditingId(partner.id); }}><Pencil className="size-3.5" /></Button><Button label="Delete" danger disabled={pending} onClick={() => void remove(selection)}><Trash2 className="size-3.5" /></Button></div>{editingId === partner.id ? <PartnerForm draft={draft} setDraft={setDraft} pending={pending} onSubmit={save} onCancel={() => setEditingId(null)} /> : null}</article>; })}</div>{editingId === "new" ? <div className="mt-3 overflow-hidden rounded-2xl border border-sky-200 bg-white"><PartnerForm draft={draft} setDraft={setDraft} pending={pending} onSubmit={save} onCancel={() => setEditingId(null)} /></div> : null}</section>;
}

function PartnerForm({ draft, setDraft, pending, onSubmit, onCancel }: { draft: Draft; setDraft: React.Dispatch<React.SetStateAction<Draft>>; pending: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => Promise<void>; onCancel: () => void }) { const field = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value })); return <form onSubmit={onSubmit} className="grid gap-3 border-t border-slate-100 p-4 md:grid-cols-2"><Input label="Name" required value={draft.name} onChange={(value) => field("name", value)} /><Input label="Slug" value={draft.slug} onChange={(value) => field("slug", value)} placeholder="Auto-generated from name" /><label><span className="mb-1.5 block text-[10px] font-black uppercase tracking-wider text-slate-400">Group</span><select value={draft.type} onChange={(event) => field("type", event.target.value as Draft["type"])} className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="LOCAL">National</option><option value="GLOBAL">Global</option></select></label><Input label="Website" type="url" value={draft.websiteUrl} onChange={(value) => field("websiteUrl", value)} placeholder="https://..." /><label className="md:col-span-2"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-wider text-slate-400">Description</span><textarea rows={3} value={draft.description} onChange={(event) => field("description", event.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:border-[#0193CD]" /></label><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={draft.isActive} onChange={(event) => field("isActive", event.target.checked)} className="accent-[#0193CD]" /> Active partner</label><div className="flex justify-end gap-2 md:col-span-2"><button type="button" onClick={onCancel} className="inline-flex h-9 items-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-500"><X className="size-3.5" /> Cancel</button><button type="submit" disabled={pending || !draft.name.trim()} className="inline-flex h-9 items-center gap-2 rounded-xl bg-[#0193CD] px-4 text-xs font-black text-white disabled:opacity-60">{pending ? <Loader2 className="size-3.5 animate-spin" /> : <Save className="size-3.5" />} Save partner</button></div></form>; }
function Input({ label, value, onChange, placeholder, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean; type?: string }) { return <label><span className="mb-1.5 block text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</span><input type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#0193CD]" /></label>; }
function Button({ label, onClick, disabled, danger, children }: { label: string; onClick: () => void; disabled?: boolean; danger?: boolean; children: React.ReactNode }) { return <button type="button" title={label} aria-label={label} disabled={disabled} onClick={onClick} className={danger ? "grid size-8 place-items-center rounded-lg border border-red-100 text-red-500 disabled:opacity-30" : "grid size-8 place-items-center rounded-lg border border-slate-200 text-slate-500 hover:text-[#0193CD] disabled:opacity-30"}>{children}</button>; }
