import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {
  ArrowRight,
  ArrowUpRight,
  BookOpenCheck,
  ChevronRight,
  Compass,
  PanelsTopLeft,
  ScanSearch,
  ShieldCheck,
  Sparkles,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import { mergeCmsContent, type CmsPageContent } from "@/lib/cms/content-page-defaults";
import { getPublishedCmsContent, getPublishedCmsPage } from "@/lib/services/cms-page.service";

export type PortfolioVariant = "overview" | "themes" | "projects" | "initiatives" | "priorities" | "humanitarian" | "climate" | "youth" | "nayon";

type PortfolioPageProps = {
  pageKey: string;
  pageName: string;
  variant: PortfolioVariant;
  defaultContent: CmsPageContent;
};

const icons: Record<string, LucideIcon> = { BookOpenCheck, Compass, PanelsTopLeft, ScanSearch, Workflow };
const themes = {
  overview: { main: "#102f49", accent: "#20a5a0", pop: "#f3b642", soft: "#f3f0e8" },
  themes: { main: "#402862", accent: "#e75c70", pop: "#57c9c0", soft: "#f4eef8" },
  projects: { main: "#1f252a", accent: "#f16d45", pop: "#f5c54f", soft: "#f0eee8" },
  initiatives: { main: "#083e47", accent: "#55c7a6", pop: "#edc455", soft: "#edf4f1" },
  priorities: { main: "#4b2444", accent: "#ee6e5e", pop: "#f1bd4c", soft: "#f7eee8" },
  humanitarian: { main: "#642d32", accent: "#f08363", pop: "#f2c25e", soft: "#f7eee9" },
  climate: { main: "#214f43", accent: "#6ac497", pop: "#e5c968", soft: "#eef4e9" },
  youth: { main: "#163b79", accent: "#46bddd", pop: "#f1c747", soft: "#edf3fc" },
  nayon: { main: "#3c286c", accent: "#a785ed", pop: "#f1bd54", soft: "#f3effa" },
} as const;

export async function getPortfolioMetadata(pageKey: string, pageName: string): Promise<Metadata> {
  const page = await getPublishedCmsPage(pageKey).catch(() => null);
  return { title: page?.seoTitle || `${pageName} | PSTC`, description: page?.seoDescription || `Explore ${pageName} and its connected PSTC programme pathways.` };
}

function Breadcrumb({ pageName, light = true }: { pageName: string; light?: boolean }) {
  return <nav aria-label="Breadcrumb" className={`flex flex-wrap items-center gap-2 text-xs font-bold ${light ? "text-white/55" : "text-current/55"}`}><Link href="/">Home</Link><ChevronRight className="size-3.5" /><Link href="/what-we-do">What We Do</Link>{pageName !== "What We Do" && <><ChevronRight className="size-3.5" /><span className={light ? "text-white" : "text-current"}>{pageName}</span></>}</nav>;
}

function Actions({ hero, dark, theme }: { hero: any; dark: boolean; theme: (typeof themes)[PortfolioVariant] }) {
  return <div className="mt-9 flex flex-wrap gap-3"><a href={hero.primaryCtaHref} className="group inline-flex items-center gap-3 rounded-full px-6 py-3.5 text-sm font-black text-[#192b3a] transition hover:-translate-y-1" style={{ backgroundColor: theme.pop }}>{hero.primaryCtaLabel}<ArrowRight className="size-4 transition group-hover:translate-x-1" /></a><Link href={hero.secondaryCtaHref} className={`inline-flex items-center gap-3 rounded-full border px-6 py-3.5 text-sm font-black transition hover:-translate-y-1 ${dark ? "border-white/20 bg-white/[.08] text-white" : "border-current/20 bg-white/40"}`}>{hero.secondaryCtaLabel}<ArrowUpRight className="size-4" /></Link></div>;
}

function Hero({ hero, variant, pageName }: { hero: any; variant: PortfolioVariant; pageName: string }) {
  const t = themes[variant];
  const img = <Image src={hero.image} alt={pageName} fill priority unoptimized={String(hero.image).endsWith(".gif")} sizes="(max-width:1024px) 100vw,52vw" className="object-cover" />;
  if (variant === "overview") return <section hidden={!hero.isVisible} className="relative min-h-[800px] overflow-hidden bg-[#102f49] text-white"><div className="absolute inset-y-0 right-0 w-full opacity-35 lg:w-[56%] lg:opacity-100">{img}<div className="absolute inset-0 bg-gradient-to-r from-[#102f49] via-[#102f49]/45 to-transparent" /></div><div className="absolute inset-0 opacity-[.05] [background-image:radial-gradient(white_1.2px,transparent_1.2px)] [background-size:26px_26px]" /><div className="container-pstc relative z-10 flex min-h-[800px] flex-col py-9"><Breadcrumb pageName={pageName} /><div className="my-auto max-w-3xl"><p className="text-xs font-black uppercase tracking-[.3em] text-[#f3b642]">{hero.eyebrow}</p><h1 className="mt-6 text-6xl font-black leading-[.88] tracking-[-.065em] sm:text-7xl lg:text-[6rem]">{hero.title}<span className="block text-[#51d1ca]">{hero.highlightedTitle}</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/62">{hero.description}</p><Actions hero={hero} dark theme={t} /></div><p className="font-mono text-[10px] font-black uppercase tracking-[.24em] text-white/45">{hero.signal}</p></div></section>;
  if (variant === "themes") return <section hidden={!hero.isVisible} className="relative min-h-[790px] overflow-hidden bg-[#f4eef8] text-[#34204f] dark:bg-[#21172f] dark:text-white"><div className="absolute -left-40 -top-52 size-[36rem] rounded-full border-[100px] border-[#57c9c0]/20" /><div className="container-pstc relative z-10 py-9"><Breadcrumb pageName={pageName} light={false} /><div className="grid min-h-[700px] items-center gap-14 lg:grid-cols-[1fr_1fr]"><div><p className="text-xs font-black uppercase tracking-[.3em] text-[#cf4660]">{hero.eyebrow} · {hero.shortCode}</p><h1 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-6xl lg:text-7xl">{hero.title}<span className="block text-[#7a58bd] dark:text-[#a98ce4]">{hero.highlightedTitle}</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">{hero.description}</p><Actions hero={hero} dark={false} theme={t} /></div><div className="relative mx-auto aspect-square w-full max-w-[570px]"><div className="absolute inset-[4%] rotate-3 overflow-hidden rounded-full border-[14px] border-white shadow-2xl dark:border-white/10">{img}</div><span className="absolute right-0 top-10 grid size-28 -rotate-6 place-items-center rounded-full bg-[#e75c70] text-center text-xs font-black uppercase tracking-[.16em] text-white">Five<br />lenses</span></div></div></div></section>;
  if (variant === "projects") return <section hidden={!hero.isVisible} className="relative min-h-[810px] overflow-hidden bg-[#1f252a] text-white"><div className="absolute inset-y-0 right-0 w-[46%]">{img}<div className="absolute inset-0 bg-gradient-to-r from-[#1f252a] via-transparent to-transparent" /><div className="absolute inset-0 bg-[#f16d45]/10 mix-blend-color" /></div><div className="absolute inset-0 [background-image:linear-gradient(rgba(255,255,255,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.06)_1px,transparent_1px)] [background-size:10%_20%]" /><div className="container-pstc relative z-10 flex min-h-[810px] flex-col py-9"><Breadcrumb pageName={pageName} /><div className="my-auto max-w-3xl"><span className="inline-block bg-[#f16d45] px-4 py-2 font-mono text-xs font-black tracking-[.23em]">{hero.shortCode}</span><h1 className="mt-8 text-6xl font-black uppercase leading-[.84] tracking-[-.07em] sm:text-7xl lg:text-[6rem]">{hero.title}<span className="block text-[#f5c54f]">{hero.highlightedTitle}</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/58">{hero.description}</p><Actions hero={hero} dark theme={t} /></div><p className="font-mono text-[10px] uppercase tracking-[.24em] text-white/40">{hero.signal}</p></div></section>;
  if (variant === "initiatives") return <section hidden={!hero.isVisible} className="relative min-h-[790px] overflow-hidden bg-[#edf4f1] text-[#153d43] dark:bg-[#102b30] dark:text-white"><div className="absolute right-0 top-0 h-full w-[38%] bg-[#edc455]" /><div className="container-pstc relative z-10 py-9"><Breadcrumb pageName={pageName} light={false} /><div className="grid min-h-[700px] items-center gap-14 lg:grid-cols-[1fr_1fr]"><div><p className="text-xs font-black uppercase tracking-[.3em] text-[#16846d]">{hero.eyebrow}</p><h1 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-6xl lg:text-7xl">{hero.title}<span className="block text-[#16846d] dark:text-[#55c7a6]">{hero.highlightedTitle}</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">{hero.description}</p><Actions hero={hero} dark={false} theme={t} /></div><div className="relative h-[570px]"><div className="absolute inset-0 overflow-hidden rounded-t-[11rem] rounded-b-2xl shadow-2xl">{img}</div><div className="absolute bottom-5 left-[-2rem] bg-[#083e47] p-6 text-white shadow-xl"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#edc455]">Institutional portfolio</p><p className="mt-2 font-black">{hero.signal}</p></div></div></div></div></section>;
  if (variant === "priorities") return <section hidden={!hero.isVisible} className="relative min-h-[780px] overflow-hidden bg-[#4b2444] text-white"><div className="absolute -right-40 -top-40 size-[38rem] rounded-full bg-[#ee6e5e]/25" /><div className="absolute -bottom-48 -left-40 size-[38rem] rounded-full border-[90px] border-white/[.05]" /><div className="container-pstc relative z-10 grid min-h-[780px] gap-12 py-9 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><Breadcrumb pageName={pageName} /><p className="mt-24 text-xs font-black uppercase tracking-[.3em] text-[#f1bd4c]">{hero.eyebrow}</p><h1 className="mt-6 text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-6xl lg:text-7xl">{hero.title}<span className="block text-[#ff917f]">{hero.highlightedTitle}</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/62">{hero.description}</p><Actions hero={hero} dark theme={t} /></div><div className="relative mx-auto aspect-square w-full max-w-[540px]"><div className="absolute inset-[5%] overflow-hidden rounded-[35%_65%_60%_40%/55%_40%_60%_45%] border-[10px] border-white/10">{img}</div><span className="absolute bottom-4 right-0 rounded-full bg-[#f1bd4c] px-7 py-4 text-xs font-black uppercase tracking-[.16em] text-[#4b2444]">{hero.shortCode}</span></div></div></section>;
  if (variant === "humanitarian") return <section hidden={!hero.isVisible} className="relative min-h-[800px] overflow-hidden bg-[#642d32] text-white"><div className="absolute inset-0">{img}<div className="absolute inset-0 bg-[#642d32]/80" /></div><div className="absolute inset-y-0 left-[12%] w-px bg-white/10" /><div className="absolute inset-y-0 right-[12%] w-px bg-white/10" /><div className="container-pstc relative z-10 flex min-h-[800px] flex-col py-9"><Breadcrumb pageName={pageName} /><div className="my-auto mx-auto max-w-5xl text-center"><p className="font-mono text-xs font-black uppercase tracking-[.35em] text-[#f2c25e]">{hero.eyebrow}</p><h1 className="mt-7 text-6xl font-black leading-[.86] tracking-[-.07em] sm:text-7xl lg:text-[6.3rem]">{hero.title}<span className="block text-[#f49a80]">{hero.highlightedTitle}</span></h1><p className="mx-auto mt-8 max-w-2xl text-lg leading-8 text-white/62">{hero.description}</p><div className="flex justify-center"><Actions hero={hero} dark theme={t} /></div></div><p className="text-center font-mono text-[10px] font-black uppercase tracking-[.25em] text-white/40">{hero.signal}</p></div></section>;
  if (variant === "climate") return <section hidden={!hero.isVisible} className="relative min-h-[790px] overflow-hidden bg-[#214f43] text-white"><div className="absolute inset-y-0 right-0 w-full opacity-45 lg:w-[55%] lg:opacity-100">{img}<div className="absolute inset-0 bg-gradient-to-r from-[#214f43] via-[#214f43]/35 to-transparent" /></div><div className="container-pstc relative z-10 flex min-h-[790px] flex-col py-9"><Breadcrumb pageName={pageName} /><div className="my-auto max-w-3xl"><span className="inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[.25em] backdrop-blur">{hero.eyebrow}</span><h1 className="mt-7 text-5xl font-black leading-[.93] tracking-[-.06em] sm:text-6xl lg:text-7xl">{hero.title}<span className="block text-[#9adeb8]">{hero.highlightedTitle}</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/65">{hero.description}</p><Actions hero={hero} dark theme={t} /></div><p className="text-xs font-black uppercase tracking-[.2em] text-[#e5c968]">{hero.signal}</p></div></section>;
  if (variant === "youth") return <section hidden={!hero.isVisible} className="relative min-h-[790px] overflow-hidden bg-[#edf3fc] text-[#17335f] dark:bg-[#10264b] dark:text-white"><div className="absolute -right-28 -top-28 size-[30rem] rounded-full bg-[#46bddd]/20" /><div className="container-pstc relative z-10 py-9"><Breadcrumb pageName={pageName} light={false} /><div className="grid min-h-[700px] items-center gap-14 lg:grid-cols-[1fr_1fr]"><div><span className="inline-block -rotate-2 bg-[#f1c747] px-4 py-2 text-xs font-black uppercase tracking-[.26em] text-[#17335f]">{hero.shortCode}</span><h1 className="mt-8 text-5xl font-black leading-[.9] tracking-[-.065em] sm:text-6xl lg:text-7xl">{hero.title}<span className="block text-[#168fb4] dark:text-[#46bddd]">{hero.highlightedTitle}</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">{hero.description}</p><Actions hero={hero} dark={false} theme={t} /></div><div className="relative h-[560px]"><div className="absolute inset-4 rotate-3 rounded-[2rem] bg-[#f1c747]" /><div className="absolute inset-0 -rotate-2 overflow-hidden rounded-[2rem] border-8 border-white shadow-2xl dark:border-white/10">{img}</div><span className="absolute -bottom-2 right-[-1rem] rounded-full bg-[#163b79] px-7 py-5 text-xs font-black uppercase tracking-[.15em] text-white">{hero.signal}</span></div></div></div></section>;
  return <section hidden={!hero.isVisible} className="relative min-h-[790px] overflow-hidden bg-[#3c286c] text-white"><div className="absolute inset-0 opacity-[.08] [background-image:radial-gradient(white_1.5px,transparent_1.5px)] [background-size:30px_30px]" /><div className="container-pstc relative z-10 grid min-h-[790px] items-center gap-14 py-9 lg:grid-cols-[.95fr_1.05fr]"><div><Breadcrumb pageName={pageName} /><p className="mt-24 text-xs font-black uppercase tracking-[.32em] text-[#f1bd54]">{hero.eyebrow}</p><h1 className="mt-6 text-6xl font-black leading-[.86] tracking-[-.07em] sm:text-7xl lg:text-[5.7rem]">{hero.title}<span className="block text-[#b99bef]">{hero.highlightedTitle}</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/62">{hero.description}</p><Actions hero={hero} dark theme={t} /></div><div className="relative mx-auto aspect-square w-full max-w-[560px]"><div className="absolute inset-[8%] overflow-hidden rounded-full border-[12px] border-[#a785ed]/30">{img}</div>{["Readiness", "Eagerness", "Commitment"].map((label, i) => <span key={label} className={`absolute rounded-full px-5 py-3 text-[10px] font-black uppercase tracking-[.16em] text-[#3c286c] ${i === 0 ? "left-0 top-[18%]" : i === 1 ? "right-0 top-[42%]" : "bottom-[10%] left-[12%]"}`} style={{ backgroundColor: i === 1 ? t.accent : t.pop }}>{label}</span>)}</div></div></section>;
}

export async function PortfolioPage({ pageKey, pageName, variant, defaultContent }: PortfolioPageProps) {
  const published = await getPublishedCmsContent<CmsPageContent>(pageKey).catch(() => null);
  const content = mergeCmsContent(defaultContent, published);
  const s = content.sections as Record<string, any>;
  const { hero, intro, features, directory, principles, cta } = s;
  const t = themes[variant];
  const angular = variant === "projects" || variant === "humanitarian";
  const organic = variant === "climate" || variant === "youth" || variant === "nayon";
  return <main className="overflow-hidden bg-background text-foreground"><Hero hero={hero} variant={variant} pageName={pageName} />
    <section hidden={!intro.isVisible} className="py-20 lg:py-28"><div className={`container-pstc grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr] lg:gap-24 ${variant === "themes" || variant === "initiatives" || variant === "climate" ? "" : ""}`}><div className={`relative mx-auto w-full max-w-xl ${variant === "themes" || variant === "priorities" || variant === "youth" ? "lg:order-2" : ""}`}><div className={`relative aspect-[4/3] overflow-hidden ${angular ? "rounded-none" : organic ? "rounded-[38%_62%_48%_52%/56%_42%_58%_44%]" : "rounded-[2rem]"}`}><Image src={intro.image} alt={`${pageName} approach`} fill unoptimized={String(intro.image).endsWith(".gif")} sizes="(max-width:1024px) 100vw,42vw" className="object-cover" /></div><span className="absolute -bottom-5 -right-5 -z-0 size-32 border-[18px] opacity-25" style={{ borderColor: t.accent, borderRadius: organic ? "9999px" : angular ? 0 : "2rem" }} /></div><div><p className="text-xs font-black uppercase tracking-[.28em]" style={{ color: t.accent }}>{intro.eyebrow}</p><h2 className="mt-4 text-4xl font-black leading-tight tracking-[-.045em] sm:text-5xl">{intro.title}<span className="block" style={{ color: t.main }}>{intro.highlightedTitle}</span></h2><p className="mt-6 text-base leading-8 text-muted-foreground">{intro.description}</p><blockquote className="mt-8 border-l-4 pl-6 text-xl font-black leading-8" style={{ borderColor: t.pop }}>{intro.statement}</blockquote><div className="mt-8 flex flex-wrap gap-2">{(intro.items ?? []).map((item: string, i: number) => <span key={`${item}-${i}`} className="rounded-full border border-border bg-card px-4 py-2 text-xs font-black">{item}</span>)}</div></div></div></section>
    <section hidden={!features.isVisible} className="relative overflow-hidden py-20 text-white lg:py-28" style={{ backgroundColor: t.main }}><div className="absolute inset-0 opacity-[.05] [background-image:radial-gradient(white_1.2px,transparent_1.2px)] [background-size:25px_25px]" /><div className="container-pstc relative"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end lg:gap-20"><div><p className="text-xs font-black uppercase tracking-[.28em]" style={{ color: t.pop }}>{features.eyebrow}</p><h2 className="mt-4 text-4xl font-black leading-tight tracking-[-.045em] sm:text-5xl">{features.title}<span className="block" style={{ color: t.accent }}>{features.highlightedTitle}</span></h2></div><p className="max-w-2xl text-base leading-8 text-white/55 lg:justify-self-end">{features.description}</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{(features.items ?? []).map((item: Record<string,string>, i: number) => { const Icon = icons[item.icon] ?? Compass; return <article key={`${item.number}-${i}`} className={`relative overflow-hidden border border-white/10 bg-white/[.06] p-7 ${angular ? "rounded-none" : organic ? "rounded-[2.5rem]" : "rounded-[1.6rem]"}`}><span className="absolute right-3 top-0 text-7xl font-black text-white/[.04]">{item.number}</span><span className="grid size-12 place-items-center rounded-full text-[#172d43]" style={{ backgroundColor: i % 2 ? t.accent : t.pop }}><Icon className="size-5" /></span><h3 className="mt-7 text-xl font-black">{item.title}</h3><p className="mt-3 text-sm leading-7 text-white/50">{item.description}</p></article>; })}</div></div></section>
    <section hidden={!directory.isVisible} id="portfolio-directory" className="py-20 lg:py-28" style={{ backgroundColor: t.soft }}><div className="container-pstc"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-end lg:gap-20"><div><p className="text-xs font-black uppercase tracking-[.28em]" style={{ color: t.accent }}>{directory.eyebrow}</p><h2 className="mt-4 text-4xl font-black leading-tight tracking-[-.045em] sm:text-5xl">{directory.title}<span className="block" style={{ color: t.main }}>{directory.highlightedTitle}</span></h2></div><p className="max-w-2xl text-base leading-8 text-muted-foreground lg:justify-self-end">{directory.description}</p></div><div className={`mt-12 grid gap-5 ${directory.items?.length === 2 ? "lg:grid-cols-2" : directory.items?.length === 5 ? "md:grid-cols-2 lg:grid-cols-6" : "md:grid-cols-2 lg:grid-cols-4"}`}>{(directory.items ?? []).map((item: Record<string,string>, i: number) => <article key={`${item.title}-${i}`} className={`group relative flex min-h-[390px] flex-col overflow-hidden bg-card shadow-[0_18px_50px_rgba(20,35,50,.09)] ${directory.items?.length === 5 ? i < 2 ? "lg:col-span-3" : "lg:col-span-2" : ""} ${angular ? "rounded-none" : organic ? "rounded-[2.3rem]" : "rounded-[1.7rem]"}`}><div className="relative h-48 overflow-hidden"><Image src={item.image} alt={item.title} fill unoptimized={String(item.image).endsWith(".gif")} sizes="(max-width:768px) 100vw,33vw" className="object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" /><span className="absolute bottom-4 left-4 rounded-full bg-white/90 px-3 py-1 text-[9px] font-black uppercase tracking-[.17em] text-[#172d43]">{item.tag}</span></div><div className="flex flex-1 flex-col p-6"><h3 className="text-2xl font-black">{item.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{item.description}</p><Link href={item.href} className="mt-auto inline-flex items-center gap-2 pt-6 text-sm font-black" style={{ color: t.main }}>{item.linkLabel}<ArrowRight className="size-4 transition group-hover:translate-x-1" /></Link></div></article>)}</div></div></section>
    <section hidden={!principles.isVisible} className="border-y border-border bg-card py-20 lg:py-28"><div className="container-pstc grid gap-12 lg:grid-cols-[.86fr_1.14fr] lg:items-center lg:gap-24"><div><p className="text-xs font-black uppercase tracking-[.28em]" style={{ color: t.accent }}>{principles.eyebrow}</p><h2 className="mt-4 text-4xl font-black leading-tight tracking-[-.045em] sm:text-5xl">{principles.title}<span className="block" style={{ color: t.main }}>{principles.highlightedTitle}</span></h2><p className="mt-6 text-base leading-8 text-muted-foreground">{principles.description}</p></div><div className="grid gap-3 sm:grid-cols-2">{(principles.items ?? []).map((item: string, i: number) => <div key={`${item}-${i}`} className="flex min-h-24 items-center gap-4 rounded-2xl border border-border bg-background p-5"><span className="grid size-10 shrink-0 place-items-center rounded-full" style={{ backgroundColor: `${t.accent}22`, color: t.accent }}><ShieldCheck className="size-5" /></span><p className="text-sm font-bold">{item}</p></div>)}</div></div></section>
    <section hidden={!cta.isVisible} className="bg-background py-20"><div className="container-pstc"><div className={`relative overflow-hidden p-8 text-white sm:p-10 lg:p-14 ${angular ? "rounded-none" : organic ? "rounded-[3rem]" : "rounded-[2rem]"}`} style={{ backgroundColor: t.main }}><Sparkles className="absolute -bottom-8 right-8 size-48 text-white/[.06]" /><div className="relative flex flex-col gap-9 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.25em]" style={{ color: t.pop }}>{cta.eyebrow}</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-4xl lg:text-5xl">{cta.title}</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/62 sm:text-base">{cta.description}</p></div><div className="flex shrink-0 flex-wrap gap-3"><Link href={cta.primaryCtaHref} className="group inline-flex items-center gap-3 rounded-full px-6 py-3.5 text-sm font-black text-[#172d43] transition hover:-translate-y-1" style={{ backgroundColor: t.pop }}>{cta.primaryCtaLabel}<ArrowRight className="size-4 transition group-hover:translate-x-1" /></Link><Link href={cta.secondaryCtaHref} className="inline-flex items-center gap-3 rounded-full border border-white/20 bg-white/[.08] px-6 py-3.5 text-sm font-black">{cta.secondaryCtaLabel}<ArrowUpRight className="size-4" /></Link></div></div></div></div></section>
  </main>;
}
